project:
  name: quickstart-linux-bastion
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: true
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-northeast-3
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-southeast-3
    - ca-central-1
    - eu-central-1
    - eu-north-1
    - eu-south-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - us-gov-east-1
    - us-gov-west-1
    - cn-north-1
    - cn-northwest-1
  template: templates/linux-bastion-entrypoint-new-vpc.template.yaml
  parameters:
    AvailabilityZones: $[taskcat_getaz_2]
    KeyPairName: --override--
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  amznlinux2hvm:
    parameters:
      BastionAMIOS: Amazon-Linux2-HVM
      BastionInstanceType: t3.medium
      RemoteAccessCIDR: 10.0.0.0/16
  centos7hvm:
    parameters:
      BastionAMIOS: CentOS-7-HVM
      BastionInstanceType: t3.medium
      RemoteAccessCIDR: 10.0.0.0/16
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - us-east-1
  sles15hvm:
    parameters:
      BastionAMIOS: SUSE-SLES-15-HVM
      BastionInstanceType: t3.medium
      RemoteAccessCIDR: 10.0.0.0/16
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - us-east-1
  us2004hvm:
    parameters:
      BastionAMIOS: Ubuntu-Server-20.04-LTS-HVM
      BastionInstanceType: t3.medium
      RemoteAccessCIDR: 10.0.0.0/16
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - us-east-1
  us2204hvm:
    parameters:
      BastionAMIOS: Ubuntu-Server-22.04-LTS-HVM
      BastionInstanceType: t3.medium
      RemoteAccessCIDR: 10.0.0.0/16
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - us-east-1
  arminst:
    parameters:
      BastionAMIOS: Amazon-Linux2-HVM-ARM
      BastionInstanceType: t4g.nano
      RemoteAccessCIDR: 10.0.0.0/16
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - us-east-1
  onlyssmaccess:
    parameters:
      BastionAMIOS: Amazon-Linux2-HVM-ARM
      BastionInstanceType: t4g.nano
      RemoteAccessCIDR: disabled-onlyssmaccess
      NumBastionHosts: 1
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - us-east-1
      - us-east-2
  multiplehosts:
    parameters:
      BastionAMIOS: Amazon-Linux2-HVM-ARM
      BastionInstanceType: t4g.nano
      RemoteAccessCIDR: 10.0.0.0/16
      NumBastionHosts: 2
    regions:
      - eu-west-1
