project:
  name: quickstart-linux-bastion
  owner: quickstart-eng@amazon.com
  lambda_source_path: functions/source
  lambda_zip_path: packages
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-east-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - us-gov-east-1
  - us-gov-west-1
  template: templates/linux-bastion-master.template
  parameters:
    AvailabilityZones: $[taskcat_getaz_2]
    BastionInstanceType: t3.large
    KeyPairName: $[taskcat_getkeypair]
    PrivateSubnet1CIDR: 10.0.0.0/19
    PrivateSubnet2CIDR: 10.0.32.0/19
    PublicSubnet1CIDR: 10.0.128.0/20
    PublicSubnet2CIDR: 10.0.144.0/20
    QSS3BucketName: $[taskcat_autobucket]
    RemoteAccessCIDR: 10.0.0.0/16
    VPCCIDR: 10.0.0.0/16
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  amznlinux2hvm:
    parameters:
      BastionAMIOS: Amazon-Linux2-HVM
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - sa-east-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - cn-north-1
      - cn-northwest-1
      - us-gov-east-1
      - us-gov-west-1
  centos7hvm:
    parameters:
      BastionAMIOS: CentOS-7-HVM
    regions:
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - us-east-1
      - us-east-2
  sles15hvm:
    parameters:
      BastionAMIOS: SUSE-SLES-15-HVM
  us1604hvm:
    parameters:
      BastionAMIOS: Ubuntu-Server-16.04-LTS-HVM
  us1804hvm:
    parameters:
      BastionAMIOS: Ubuntu-Server-18.04-LTS-HVM
