AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation stack for the regional infrastructure shared by linux bastion hosts.  Must be deployed before any bastion stacks. Borrows from AWS Quickstart templates.  
Parameters:
  BastionLogGroupName:
    Type: String
    Default: bastion
  BastionLogRetentionDays:
    Type: String
    Default: 365
Mappings:
  RegionMap:
    us-west-2:
      BastionVPC: vpc-828464fb
      BastionCIDR: 172.31.252.0/24
    us-east-1:
      BastionVPC: vpc-03261b90f9d914c30
      BastionCIDR: 172.20.252.0/24
Resources:
  BastionMainLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Ref BastionLogGroupName
      RetentionInDays: !Ref BastionLogRetentionDays
  SSHMetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: !Ref BastionMainLogGroup
      FilterPattern: ON FROM USER PWD
      MetricTransformations:
        - MetricName: SSHCommandCount
          MetricValue: '1'
          MetricNamespace: 'Bastion'
  BastionSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      # Let Cloudformation choose an available AZ (recommended), or uncomment to specify your AZ.
      # AvailabilityZone: !Sub ${AWS::Region}a
      CidrBlock: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - BastionCIDR
      MapPublicIpOnLaunch: true
      VpcId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - BastionVPC
      Tags: 
        - Key: Name
          Value: !Sub ${AWS::StackName}-subnet
  RDSBastionSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub ${AWS::StackName}-to-rds
      GroupDescription: Provides bastion hosts access to RDS databases
      VpcId: !FindInMap [RegionMap, !Ref AWS::Region, BastionVPC]
  AppBastionSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub ${AWS::StackName}-to-app
      GroupDescription: Provides bastion hosts access to App hosts
      VpcId: !FindInMap [RegionMap, !Ref AWS::Region, BastionVPC]
Outputs:
  CloudWatchLogs:
    Description: CloudWatch Logs GroupName. Your SSH logs will be stored here.
    Value: !Ref BastionMainLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'
  RDSBastionSecurityGroup:
    Description: Security group for bastion hosts to access RDS databases
    Value: !GetAtt RDSBastionSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-RDSBastionSecurityGroup'
  AppBastionSecurityGroup:
    Description: Security group for bastion hosts to access App hosts
    Value: !GetAtt AppBastionSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-AppBastionSecurityGroup'
  BastionSubnet:
    Description: Subnet for bastion hosts.
    Value: !Ref BastionSubnet
    Export:
      Name: !Sub '${AWS::StackName}-BastionSubnet'
  BastionVPC:
    Description: VPC for bastion hosts.
    Value: !FindInMap [ RegionMap, !Ref AWS::Region, BastionVPC]
    Export:
      Name: !Sub '${AWS::StackName}-BastionVPC'
