




##############################################
#     This is only a sample message          #
#--------------------------------------------#
#     If you are not an authorized user!     #
#     Please disconnect Immediately!         #
##############################################
#                                            #
#  You can customize the above message by    #
#  updating the inputs provided at launch    #
#                                            #
#  NOTE: You can also disable this message   #
#  by setting the EnableBanner option        #
#  to False                                  #
**********************************************
